# -*- coding: utf-8 -*-
"""Plot Rashba and mobility vs density from extracted parameters.

The csv file to read is expected to have been generated by
extract_soi_from_wal.py

"""

# =============================================================================
# --- Parameters --------------------------------------------------------------
# =============================================================================

#: Path to the csv fild holding the data
PATH = ('/Users/mdartiailh/Documents/PostDocNYU/DataAnalysis/WAL/JS124/'
        'average_rashba_only/JS138_124HB_BM003_004_wal_analysis_avg.csv')

#: Density column
DENSITY_COLUMN = 'Density (m^-2)'

#: Mobility column
MOBILITY_COLUMN = 'Mobility (m^2V^-1s^-1)'

#: SOI column
SOI_COLUMN = 'Rashba SOI (meV.A)'

#: Densities to mark on the SOI plot (in 1e12 cm^-2)
DENSITIES = [1.3, 1.9, 3.8]

#: Number of points on which to average the SOI strength to compute stderr
STDERR_COMPUTATION = 3

# =============================================================================
# --- Execution ---------------------------------------------------------------
# =============================================================================

import os
import time

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

plt.rcParams.update({'font.size': 14})
plt.rcParams.update({'pdf.fonttype': 42})

data = pd.read_csv(PATH, comment='#')

density = np.array(data[DENSITY_COLUMN][1:])
mobility = np.array(data[MOBILITY_COLUMN][1:])
rashba = np.array(data[SOI_COLUMN][1:])

density = np.mean(density.reshape((-1, STDERR_COMPUTATION)), axis=1)
mean_mob = np.mean(mobility.reshape((-1, STDERR_COMPUTATION)), axis=1)
std_mob = np.std(mobility.reshape((-1, STDERR_COMPUTATION)), axis=1)
mean_soi = np.mean(rashba.reshape((-1, STDERR_COMPUTATION)), axis=1)
std_soi = np.std(rashba.reshape((-1, STDERR_COMPUTATION)), axis=1)

fig, (ax1, ax2) = plt.subplots(1, 2, sharex=True, constrained_layout=True, figsize=(15,4))

ax1.errorbar(density/1e4, mean_mob*1e4, std_mob*1e4, fmt='+', color='C2')
ax1.set_ylabel('Mobility (cm$^{-2}$V${^-1}$s$^{-1}$)')
ax1.set_xlabel('Density (cm$^{-2}$)')

ax2.errorbar(density/1e4, mean_soi, std_soi, fmt='+',)
ax2.set_ylabel('Rashba SOI (meV.A)')
ax2.set_xlabel('Density (cm$^{-2}$)')
for n in DENSITIES:
    ax2.axvline(n*1e12, ymin=0.95, color='k')

plt.show()
