"""Fit current-phase relations to extract transparency.

This script depends on aggregated data generated by `./aggregate.py`.

Wafer:      JS512
Piece:      C09
Layout:     FlSq4to1-8.gds
Devices:    4to1, 4to2, 4to7
Cooldown:   WFS02
Scans:      112, 125, 137
"""


import h5py
import numpy as np
from matplotlib import pyplot as plt

from shabanipy.constants import VECTOR10_AMPS_PER_TESLA_X as A_PER_T
from shabanipy.jj.plotting_general import plot_fraunhofer

with h5py.File("data_aggregated.hdf5", "r") as f:
    squid4to1 = f["cpr"]["device::FlSq4to1"]
    bfield = squid4to1["x magnet source current"].__array__() / A_PER_T
    ibias = squid4to1["dc current bias"].__array__()
    dmm = squid4to1["dmm"].__array__() / 100
    lockin = squid4to1["lock-in"].__array__()

plot_fraunhofer(bfield, ibias, np.abs(lockin))
plt.show()
